version: '3'

volumes:
  mongodb_data:
      driver: local

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: "mongodb"
    ports:
      - 27017:27017
  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: .
    restart: always
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - PUBLIC_URL
      - REACT_APP_API_BASE
      - REACT_APP_BASE
      - NODE_ENV=production
    depends_on:
      - keycloak
      - api
  api:
    build:
      dockerfile: api.Dockerfile
      context: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - SONG_COUNTS
      - SHUFFLE
      - PORT=3000
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
      - MONGOOSE_CONNECTION_STRING
      - NODE_ENV=production
    depends_on:
      - keycloak
      - mongodb
