services:
  frontend:
    environment:
      - PORT=5000
      - PUBLIC_URL=http://192.168.178.50/boolean-lists
      - REACT_APP_API_BASE=http://192.168.178.50/boolean-lists-api
      - REACT_APP_BASE=http://192.168.178.50/boolean-lists
      - NODE_ENV=development
    labels:
      - traefik.http.routers.boolean-lists-frontend.rule=Host(`192.168.178.50`) && PathPrefix(`/boolean-lists`)
  api:
    environment:
      - SONG_COUNTS
      - SHUFFLE
      - PORT=3000
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI=http://192.168.178.50/auth/spotify/callback
      - MONGOOSE_CONNECTION_STRING=mongodb://root:example@mongodb
      - NODE_ENV=development
    labels:
      - traefik.http.routers.boolean-lists-api.rule=Host(`192.168.178.50`) && PathPrefix(`/boolean-lists-api`)

networks:
  web:
    external: true
  backend:
