version: '3'

volumes:
  mysql_data:
      driver: local

services:
  # stores data for keycloak
  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  keycloak:
      image: jboss/keycloak
      environment:
        DB_VENDOR: h2
#        DB_ADDR: mysql
#        DB_DATABASE: keycloak
#        DB_USER: keycloak
#        DB_PASSWORD: ${DB_PASSWORD}
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
#      depends_on:
#        - mysql

    # stores information for the backend
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: "mongodb"
    ports:
      - 27017:27017
